language: generic
sudo: required
services:
  - docker

before_install:
  -  docker build -t denyskisliak/docker-first -f ./Docker_App/Dockerfile.dev ./Docker_App

script:
  - docker run -e CI=true denyskisliak/docker-first mvn test -DargLine="-Xss512k"

after_success:
  - docker build -t denyskisliak/docker-first ./Docker_App
  - docker build -t denyskisliak/docker-sec  ./second_service

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push denyskisliak/docker-first
  - docker push denyskisliak/docker-sec