version: '3'
services:
  postgres-db:
    image: postgres:16-alpine3.19
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  java-app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: Docker_App
      dockerfile: Dockerfile.dev
    container_name: app
    depends_on:
      - postgres-db
      - second_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  second_app:
    image: 'second-app:latest'
    build:
      context: ./second_service
      dockerfile: Dockerfile.dev
    container_name: sec_app
    ports:
      - "8081:8081"